"""SimPy models and finite-run accounting for the MATH 565 queue companion."""
from dataclasses import dataclass
import numpy as np
import simpy


@dataclass
class QueueRun:
    time: float
    customers: list
    tandem: bool
    capacity: int | None

    def trajectory(self):
        events = [(0.0, 0)]
        for c in self.customers:
            events.append((c['arrival'], 1))
            if 'departure' in c:
                events.append((c['departure'], -1))
        events.sort(key=lambda e: e[0])
        times, changes = np.array(events).T
        return np.r_[times, self.time], np.r_[np.cumsum(changes), sum(changes)]

    def summary(self):
        t = self.time
        completed = [c for c in self.customers if 'departure' in c]
        def duration(c, start, end):
            if start not in c:
                return 0.0
            return max(0.0, min(c.get(end, t), t) - c[start])
        def mean(values):
            return float(np.mean(values)) if values else np.nan
        residence = sum(duration(c, 'arrival', 'departure') for c in self.customers)
        total_completed = sum(c['departure'] - c['arrival'] for c in completed)
        out = {
            'sim_time': t, 'arrivals': len(self.customers), 'departures': len(completed),
            'remaining': len(self.customers) - len(completed),
            'arrival_rate': len(self.customers) / t,
            'throughput': len(completed) / t,
            'avg_N': residence / t,
            'avg_W': mean([c['departure'] - c['arrival'] for c in completed]),
            'avg_wait_1': mean([c['start_1'] - c['arrival'] for c in completed]),
            'busy_1': sum(duration(c, 'start_1', 'end_1') for c in self.customers) / t,
            'completed_residence_per_time': total_completed / t,
            'unfinished_residence_per_time': (residence - total_completed) / t,
        }
        if self.tandem:
            out.update(
                busy_2=sum(duration(c, 'start_2', 'departure') for c in self.customers) / t,
                blocked_1=sum(duration(c, 'end_1', 'transfer') for c in self.customers) / t,
                avg_block=mean([c['transfer'] - c['end_1'] for c in completed]),
                avg_wait_2=mean([c['start_2'] - c['transfer'] for c in completed]),
                capacity=self.capacity,
            )
        return out


def simulate_queue(arrivals, service_1, service_2=None, *, capacity=1,
                   t_end=None, n_complete=None):
    """FCFS single server or two-stage blocking-after-service drive-through.

    Inputs are pre-generated by customer index, allowing coupled comparisons.
    Stop at t_end (events at t_end excluded), at n_complete departures, or the
    earlier of the two. Service at stage 1 retains its resource while waiting
    for a pickup slot; capacity includes the customer in service at pickup.
    """
    arrivals = np.asarray(arrivals, dtype=float)
    service_1 = np.asarray(service_1, dtype=float)
    tandem = service_2 is not None
    service_2 = np.asarray(service_2, dtype=float) if tandem else None
    if (arrivals.ndim != 1 or len(arrivals) == 0 or
            not np.all(np.isfinite(arrivals)) or np.any(arrivals < 0) or
            np.any(np.diff(arrivals) < 0)):
        raise ValueError('arrivals must be a nonempty sorted vector of finite nonnegative times')
    for service in [service_1] + ([service_2] if tandem else []):
        if service.shape != arrivals.shape or not np.all(np.isfinite(service)) or np.any(service <= 0):
            raise ValueError('each customer needs a positive finite service time at each stage')
    if t_end is None and n_complete is None:
        raise ValueError('supply a time horizon or departure count')
    if t_end is not None and (not np.isfinite(t_end) or t_end <= 0):
        raise ValueError('t_end must be positive and finite')
    if n_complete is not None and (int(n_complete) != n_complete or not 1 <= n_complete <= len(arrivals)):
        raise ValueError('n_complete must be an integer within the supplied cohort')
    if tandem and (int(capacity) != capacity or capacity < 1):
        raise ValueError('capacity must be a positive integer')
    env = simpy.Environment()
    order = simpy.Resource(env, capacity=1)
    pickup = simpy.Resource(env, capacity=1) if tandem else None
    slots = simpy.Resource(env, capacity=int(capacity)) if tandem else None
    done = env.event()
    records = []
    departed = 0

    def customer(i):
        nonlocal departed
        c = {'id': i, 'arrival': env.now}
        records.append(c)
        with order.request() as request:
            yield request
            c['start_1'] = env.now
            yield env.timeout(service_1[i])
            c['end_1'] = env.now
            if tandem:
                slot = slots.request()
                yield slot  # Keep the order window occupied while blocked.
                c['transfer'] = env.now
        if tandem:
            with pickup.request() as request:
                yield request
                c['start_2'] = env.now
                yield env.timeout(service_2[i])
                c['departure'] = env.now
            slots.release(slot)
        else:
            c['departure'] = env.now
        departed += 1
        if departed == n_complete:
            done.succeed()

    def source():
        for i, arrival in enumerate(arrivals):
            yield env.timeout(arrival - env.now)
            env.process(customer(i))

    env.process(source())
    # Process only events strictly before a finite horizon. A departure-count
    # stop includes the departure that triggers it, without taking another step.
    horizon = float(t_end) if t_end is not None else np.inf
    while not done.triggered and env.peek() < horizon:
        env.step()
    stop_time = float(env.now) if done.triggered else horizon
    if not np.isfinite(stop_time):
        raise RuntimeError('event queue exhausted before the requested departure')
    return QueueRun(stop_time, records, tandem, int(capacity) if tandem else None)
